# Generated by Django 5.2.12 on 2026-03-30 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_initial'),
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_station',
            field=models.ForeignKey(blank=True, help_text='Simba Oil / station-facing staff; approvers may optionally be scoped to a station.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='fuel.fuelstation'),
        ),
    ]
