# Generated by Django 5.2.4 on 2026-03-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=128)),
                ('actor_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('DRIVER', 'Driver'), ('APPROVER', 'Approver'), ('SIMBA_OIL', 'Simba Oil'), ('QSE', 'QSE')], max_length=20)),
                ('target', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Kerosene', 'Kerosene')], max_length=16)),
                ('price_per_litre', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_from', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='FuelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True)),
                ('fuel_type', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Kerosene', 'Kerosene')], max_length=16)),
                ('quantity_is_money', models.BooleanField(default=False)),
                ('quantity_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('litres_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_litres', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('issued_litres', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('attendant_name', models.CharField(blank=True, max_length=128)),
                ('request_datetime', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('FUEL_ISSUED', 'Fuel issued'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('mvfo_status', models.CharField(choices=[('CREATED', 'Created'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted'), ('COLLECTION', 'Collection'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('INCOMPLETE', 'Incomplete'), ('COLLECTED', 'Collected')], default='CREATED', max_length=20)),
                ('owner_role', models.CharField(choices=[('ADMIN', 'Admin'), ('DRIVER', 'Driver'), ('APPROVER', 'Approver'), ('SIMBA_OIL', 'Simba Oil'), ('QSE', 'QSE')], max_length=20)),
                ('price_per_litre', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('partial_reason', models.TextField(blank=True)),
                ('incomplete_reason', models.TextField(blank=True)),
                ('has_pump_meter_photo', models.BooleanField(default=False)),
                ('has_gps_capture', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-request_datetime'],
            },
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=128)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('contact_phone', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OperationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('master_data', 'Master data'), ('mvfo', 'MVFO'), ('security', 'Security'), ('assignment', 'Assignment')], max_length=32)),
                ('summary', models.CharField(max_length=512)),
                ('actor_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('DRIVER', 'Driver'), ('APPROVER', 'Approver'), ('SIMBA_OIL', 'Simba Oil'), ('QSE', 'QSE')], max_length=20)),
                ('related_entity', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Operation activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RequestTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('actor_name', models.CharField(max_length=255)),
                ('actor_role', models.CharField(choices=[('ADMIN', 'Admin'), ('DRIVER', 'Driver'), ('APPROVER', 'Approver'), ('SIMBA_OIL', 'Simba Oil'), ('QSE', 'QSE')], max_length=20)),
                ('at', models.DateTimeField()),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(db_index=True, max_length=32, unique=True)),
                ('make', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('year', models.PositiveSmallIntegerField()),
                ('default_fuel_type', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Kerosene', 'Kerosene')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
    ]
