# Generated by Django 5.2.4 on 2026-03-29 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fuelprice',
            name='set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_prices_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fuelrequest',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_requests', to='fuel.driver'),
        ),
        migrations.AddField(
            model_name='fuelrequest',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_requests', to='fuel.fuelstation'),
        ),
        migrations.AddField(
            model_name='fuelprice',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_prices', to='fuel.fuelstation'),
        ),
        migrations.AddField(
            model_name='driver',
            name='assigned_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='fuel.fuelstation'),
        ),
        migrations.AddField(
            model_name='requesttimelineevent',
            name='fuel_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='fuel.fuelrequest'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='fuel.driver'),
        ),
        migrations.AddField(
            model_name='fuelrequest',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_requests', to='fuel.vehicle'),
        ),
        migrations.AddIndex(
            model_name='fuelprice',
            index=models.Index(fields=['station', 'fuel_type', '-effective_from'], name='fuel_fuelpr_station_a8b6d1_idx'),
        ),
    ]
