# Generated by Django 5.2.4 on 2026-04-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrequest',
            name='gps_capture_text',
            field=models.TextField(blank=True, help_text='Lat/lng and timestamp from the station device (Simba Oil capture).'),
        ),
        migrations.AddField(
            model_name='fuelrequest',
            name='pump_meter_photo_base64',
            field=models.TextField(blank=True, help_text='Base64-encoded pump meter image (data URL prefix optional).'),
        ),
    ]
